package br.org.caixa.service;

import java.util.stream.Collectors;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.transaction.Transactional;

import br.org.caixa.model.simulador.FilaSimulador;
import br.org.caixa.persistencia.entidade.MensagemServico;
import br.org.caixa.persistencia.entidade.ServicoSibarKey;
import br.org.caixa.persistencia.repository.MensagemFilaRepository;
import br.org.caixa.persistencia.repository.MensagemServicoRepository;

@ApplicationScoped
public class SimuladorServiceImpl implements SimuladorService {
	
	@Inject
	MensagemFilaRepository mensagemFilaRepository;
	
	@Inject
	MensagemServicoRepository mensagemServicoRepository;
	
	@Override
	@Transactional
	public String obterMensagem(FilaSimulador filaSimulador) {
		
		var msgFila = mensagemFilaRepository.findAtivoByNomeFila(filaSimulador.getFila()).getMensagem();
		
		var listaServicoKey = filaSimulador.getListaIdServico().stream().map(x -> 
				new ServicoSibarKey(x.getServico(), x.getOperacao(), x.getVersao())
			).collect(Collectors.toList());
		
		var servicos = mensagemServicoRepository.findAtivoByServico(listaServicoKey);
		
		var msgServicos  = servicos.stream().map(MensagemServico::getMensagem).collect(Collectors.joining());
		
		msgFila = msgFila.replace("${tarefas}", msgServicos);
		
		return msgFila;
		//return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><multicanal:SERVICO_SAIDA xmlns:multicanal=\"http://caixa.gov.br/sibar/multicanal/orquestracao\" xmlns:sibar_base=\"http://caixa.gov.br/sibar\"><sibar_base:HEADER><VERSAO>1.0</VERSAO><USUARIO_SERVICO>SIBCS01D</USUARIO_SERVICO><OPERACAO>SERVICO_MIGRADO</OPERACAO><SISTEMA_ORIGEM>SIIBC</SISTEMA_ORIGEM><UNIDADE>7924</UNIDADE><DATA_HORA>20210504103917</DATA_HORA></sibar_base:HEADER><COD_RETORNO>00</COD_RETORNO><ORIGEM_RETORNO>BARRAMENTO_MULTICANAL</ORIGEM_RETORNO><MSG_RETORNO>INTEGRACAO REALIZADA COM SUCESSO.</MSG_RETORNO><validapermissao:VALIDA_PERMISSAO_SAIDA xmlns:validapermissao=\"http://caixa.gov.br/sibar/valida_permissao\"><CONTROLE_NEGOCIAL><ORIGEM_RETORNO>SIPER</ORIGEM_RETORNO><COD_RETORNO>00</COD_RETORNO><MENSAGENS><RETORNO>(0) - () - ()</RETORNO></MENSAGENS></CONTROLE_NEGOCIAL><OPCAO>1</OPCAO><CPF>60207027404</CPF><TOKEN><ACAO>2</ACAO><SESSAO>2MV6E+20X6ginoW07b1B5N2h.sinbc03</SESSAO><ENDERECO_IP>10.192.227.254</ENDERECO_IP><TOKEN_SESSAO>PEDEP01FLAVIA       hIx4VPSxZPF57sE6cXt3I4fJUP3Yx8phEkPqAWFwTME76yIBhj88SCZSkaxa</TOKEN_SESSAO></TOKEN><CONTA_NSGD><UNIDADE>7924</UNIDADE><PRODUTO>1288</PRODUTO><NUMERO>900000005</NUMERO><DV>5</DV></CONTA_NSGD><FLAG_TP_LOGIN>1</FLAG_TP_LOGIN><DT_MOVTO_SIPER>20210504</DT_MOVTO_SIPER><NSU_SIPER>945890</NSU_SIPER></validapermissao:VALIDA_PERMISSAO_SAIDA><consultaboletopagamento:CONSULTA_COBRANCA_BANCARIA_SAIDA xmlns:consultaboletopagamento=\"http://caixa.gov.br/sibar/consulta_cobranca_bancaria/pagamento\"><CONTROLE_NEGOCIAL><ORIGEM_RETORNO>SIGCB</ORIGEM_RETORNO><COD_RETORNO>000</COD_RETORNO><MENSAGENS><RETORNO>(2024) -08-260000CONSULTA REALIZADA COM SUCESSO</RETORNO></MENSAGENS></CONTROLE_NEGOCIAL><CONSULTA_BOLETO_PAGAMENTO><FLAG_NOVA_COBRANCA>S</FLAG_NOVA_COBRANCA><SITUACAO_CONTINGENCIA>SEM_CONTINGENCIA</SITUACAO_CONTINGENCIA><FLAG_HABITACAO>N</FLAG_HABITACAO><TIPO_BOLETO>CARTAO DE CREDITO</TIPO_BOLETO><TITULO><NOSSO_NUMERO><NUMERO>14000000009991103</NUMERO><DV>0</DV></NOSSO_NUMERO><BENEFICIARIO_ORIGINAL><CNPJ>360305000104</CNPJ><RAZAO_SOCIAL>THIAGO JOSE TORREO CHACON</RAZAO_SOCIAL><NOME_FANTASIA>THIAGO JOSE TORREO CHACON</NOME_FANTASIA><CODIGO>806238</CODIGO><DV>2</DV></BENEFICIARIO_ORIGINAL><PAGADOR><CPF>95618279649</CPF><NOME>TESTE PAGADOR CARTAO DE CREDITO</NOME></PAGADOR><CODIGO_BARRAS>10498882100001000008062382000100040099911035</CODIGO_BARRAS><LINHA_DIGITAVEL>10498062338200010004800999110356888210000100000</LINHA_DIGITAVEL><DATA_VENCIMENTO>2021-12-01</DATA_VENCIMENTO><VALOR>1000.00</VALOR><MINIMO><VALOR>10.00</VALOR></MINIMO><MAXIMO><VALOR>0.00</VALOR></MAXIMO><PARTICIPANTE_DESTINATARIO><ISPB>00360305</ISPB><CODIGO_BANCO>104</CODIGO_BANCO></PARTICIPANTE_DESTINATARIO></TITULO><RECEBE_VALOR_DIVERGENTE>QUALQUER_VALOR</RECEBE_VALOR_DIVERGENTE><FLAG_RECEBIMENTO_CHEQUE>N</FLAG_RECEBIMENTO_CHEQUE><FLAG_PAGAMENTO_PARCIAL>S</FLAG_PAGAMENTO_PARCIAL><QUANTIDADE_PAGAMENTO_PARCIAL_PERMITIDO>99</QUANTIDADE_PAGAMENTO_PARCIAL_PERMITIDO><QUANTIDADE_PAGAMENTO_PARCIAL_REGISTRADO>2</QUANTIDADE_PAGAMENTO_PARCIAL_REGISTRADO><MODELO_CALCULO>01</MODELO_CALCULO><CALCULOS><CALCULO_CAIXA><VALOR_JUROS>0.00</VALOR_JUROS><VALOR_MULTA>0.00</VALOR_MULTA><VALOR_DESCONTO>0.00</VALOR_DESCONTO><VALOR_TOTAL>0.00</VALOR_TOTAL><DATA_VALIDADE_CALCULO>2021-05-04</DATA_VALIDADE_CALCULO><VALOR_IOF>0.00</VALOR_IOF><VALOR_ABATIMENTO>0.00</VALOR_ABATIMENTO><DATA_VENCIMENTO_UTIL>2021-12-01</DATA_VENCIMENTO_UTIL><DATA_CALCULO>2021-05-04</DATA_CALCULO></CALCULO_CAIXA></CALCULOS><FLAG_ULTIMA_PARCELA_VIAVEL>S</FLAG_ULTIMA_PARCELA_VIAVEL><NUMERO_PARCELA_ATUAL>3</NUMERO_PARCELA_ATUAL></CONSULTA_BOLETO_PAGAMENTO></consultaboletopagamento:CONSULTA_COBRANCA_BANCARIA_SAIDA><consultaregrasboleto:CONSULTA_REGRAS_BOLETO_SAIDA xmlns:consultaregrasboleto=\"http://caixa.gov.br/simtx/consulta_boleto/regras/v1/ns\"><CONTROLE_NEGOCIAL><ORIGEM_RETORNO>SIMTX</ORIGEM_RETORNO><COD_RETORNO>00</COD_RETORNO><MENSAGENS><RETORNO>TRANSACAO REALIZADA COM SUCESSO</RETORNO></MENSAGENS></CONTROLE_NEGOCIAL><FORMA_RECEBIMENTO>QUALQUER_VALOR</FORMA_RECEBIMENTO></consultaregrasboleto:CONSULTA_REGRAS_BOLETO_SAIDA></multicanal:SERVICO_SAIDA>";
	}

}
